Add database
sabolenok/java-filmorate pull request #3
Opened 2022-10-23 08:57 UTC by sabolenok

Спринт #12 финальное задание

2022-10-24 04:56 UTC, sergeymamonov requested changes
В проекте не используется исключение CustomValidationException.
Если можно воспользоваться аннотацией Lombok для генерации кода конструктора, то лучше так и сделать, а не писать конструктор руками. Относится к тем классам, где сейчас написан конструктор руками и где можно заменить.

2022-10-24 04:56 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +        Assertions.assertThrows(NotFoundException.class, () -> userStorage.findUserById(42));
Еще хорошо бы проверить сообщение в ошибке, что оно соответствует ожидаемому.

2022-10-24 04:56 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +    public MpaController(FilmService filmService) {
Зачем писать конструктор руками, если можно воспользоваться аннотацией Lombok?

2022-10-24 04:56 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private int reverseCompare(Film f0, Film f1) {
Метод нигде не используется.

2022-10-24 15:12 UTC, sabolenok commented
Замечания исправлены

2022-10-25 03:42 UTC, sergeymamonov approved these changes

2022-10-25 11:15 UTC, merged